# Generated by Django 4.2.4 on 2023-08-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('RUB', 'RUB'), ('CNY', 'CNY')], default='RUB', max_length=3),
        ),
    ]
