# Generated by Django 4.2.4 on 2023-08-31 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_commentuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentuser',
            options={},
        ),
        migrations.AddField(
            model_name='commentuser',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='commentuser',
            name='name_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentuser_product', to='magazine.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='commentuser',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
